name: task_sup
channels:
  - defaults
dependencies:
  - pip=23.3.1
  - python=3.10.14
  - pip:
      - accelerate==0.30.0
      - torch==2.2.1
      - transformers==4.40.1
      - triton==2.2.0
      - openai==1.33.0
      - tiktoken==0.7.0
      - pytz